#12 debug page
Northeastern-Electric-Racing/Nero pull request #13
Opened 2023-02-08 19:34 UTC by Peyton-McKee

## Changes

Factored out home to a page, created debug table, created functions for getting input from mock model.

## Notes

Not sure this is the best way to do this, curious if I should be using a different data structure for the table. Also curious on the best way to get input from model/can...

## Screenshots
<img width="1097" alt="Screen Shot 2023-02-08 at 2 33 03 PM" src="https://user-images.githubusercontent.com/113635669/217632845-0af8c9c7-8f36-413e-89f8-fea0c6f3583f.png">

## To Do

_Any remaining things that need to get done_

Can button input/telemetry hub information on name/ units 

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #12  (issue #)

2023-02-10 02:39 UTC, mccauleyma commented
REEEEEE this is making me realize that we probably do need to rethink the dashboard <-> MPU interface. @nwdepatie I think we're gonna need to send button inputs to dashboard and then have dashboard keep track of a vehicle state and send that to MPU

2023-02-14 01:16 UTC, anthonybernardi requested changes
can you leave documentation especially throughout the debug stuff because just looking at it it's hard to understand

2023-02-14 01:16 UTC, anthonybernardi commented on nero_view.py
> +        self.controller = RaspberryModel() if self.isLinux else MockModel()
self.model

2023-02-14 01:16 UTC, anthonybernardi commented on mock_model.py
> +        return [debug.Table_Row_Value(0, "speed", self.mph, "mph"), debug.Table_Row_Value(1, "status", self.status, "bool"), debug.Table_Row_Value(2, "dir", self.dir, "bool"), debug.Table_Row_Value(3
this should be represented and stored as a class

2023-02-14 01:16 UTC, anthonybernardi commented on pages/debug.py
> +class Table_Row_Frame(Frame):
all these classes sohuld start with Debug_

2023-02-14 01:16 UTC, anthonybernardi commented on raspberry_model.py
> +    def get_generic(self, id: int) -> Optional[int]:
get_by_id

2023-02-14 01:16 UTC, anthonybernardi commented on nero_view.py
> +        self.frames = {}
if we're doing a dictionary, we shouldn't do index and should do names instead

2023-02-14 01:16 UTC, anthonybernardi commented on nero_view.py
> +        self.frames[0].mph.configure(text=new_mph_text)
store the home frame as `self.home_frame` as well as putting it in the dict that way we can directly access it here

2023-02-14 01:16 UTC, anthonybernardi commented on nero_view.py
> +        for F in (home.Home, debug.Debug_Table):
F????? what is F

2023-02-14 01:16 UTC, anthonybernardi commented on nero_view.py
> +            frame = F(parent=container, controller=self)
does it need to be called controller?

2023-02-14 01:43 UTC, Peyton-McKee commented on mock_model.py
> +        return [debug.Table_Row_Value(0, "speed", self.mph, "mph"), debug.Table_Row_Value(1, "status", self.status, "bool"), debug.Table_Row_Value(2, "dir", self.dir, "bool"), debug.Table_Row_Value(3
stored as a class or an object?

2023-02-14 01:44 UTC, Peyton-McKee commented on nero_view.py
> +            frame = F(parent=container, controller=self)
no

2023-02-14 01:44 UTC, Peyton-McKee commented on nero_view.py
> +        self.frames[0].mph.configure(text=new_mph_text)
what about that case with the view_index

2023-02-14 15:33 UTC, Peyton-McKee commented on nero_view.py
> +        for F in (home.Home, debug.Debug_Table):
Frame

2023-02-15 16:05 UTC, anthonybernardi commented on mock_model.py
> +        return [debug.Table_Row_Value(0, "speed", self.mph, "mph"), debug.Table_Row_Value(1, "status", self.status, "bool"), debug.Table_Row_Value(2, "dir", self.dir, "bool"), debug.Table_Row_Value(3
what's the difference

2023-02-15 16:06 UTC, anthonybernardi commented on mock_model.py
> +        return [debug.Table_Row_Value(0, "speed", self.mph, "mph"), debug.Table_Row_Value(1, "status", self.status, "bool"), debug.Table_Row_Value(2, "dir", self.dir, "bool"), debug.Table_Row_Value(3
(class)

2023-02-15 16:21 UTC, Peyton-McKee commented on mock_model.py
> +        return [debug.Table_Row_Value(0, "speed", self.mph, "mph"), debug.Table_Row_Value(1, "status", self.status, "bool"), debug.Table_Row_Value(2, "dir", self.dir, "bool"), debug.Table_Row_Value(3
I think Im misunderstanding what your saying, but how would i access the mph, lv batt and stuff like that from a different class?

2023-02-23 20:27 UTC, anthonybernardi approved these changes
merging cuz it's good enough for now and this pr cannot get bigger

2023-02-23 20:27 UTC, merged