#32 Incremental storage of plotting data
Northeastern-Electric-Racing/Nero pull request #35
Opened 2023-03-26 02:03 UTC by Peyton-McKee

## Changes

Trying to implement incremental storage but its just not working and i dont understand why. I think it might have something to do with refs, but whenver i update one array, they all get updated, its quite frustrating and i cant figure out why this is happening.

## Checklist

It can be helpful to check the `Checks` and `Files changed` tabs.
Please review the [contributor guide](https://nerdocs.atlassian.net/wiki/spaces/NER/pages/8060929/Software+Contributor+Guide) and reach out to your Tech Lead if anything is unclear.
Please request reviewers and ping on slack only after you've gone through this whole checklist.

- [ ] All commits are tagged with the ticket number
- [ ] No linting errors / newline at end of file warnings
- [ ] All code follows repository-configured formatting
- [ ] No merge conflicts
- [ ] All checks passing
- [ ] Screenshots of UI changes (see Screenshots section)
- [ ] Remove any non-applicable sections of this template
- [ ] Assign the PR to yourself
- [ ] Request reviewers & ping on Slack
- [ ] PR is linked to the ticket (fill in the closes line below)

Closes #32  (issue #)

2023-03-26 20:34 UTC, anthonybernardi requested changes
skimming this, i have no idea what these things mean (pinned_data_600 pinned_data_300 etc etc) which means the code itself is not readable enough

if you want more people to be able to work on NERO, then you need to think about what you're writing from the eyes of someone who has no idea what nero is

2023-03-27 14:50 UTC, anthonybernardi requested changes
noice

2023-03-27 14:50 UTC, anthonybernardi commented on models/model.py
> +        # Individual arrays for each time interval (30s, 60s, 120s, 300s, 600s)
don't need this anymore

2023-03-27 14:50 UTC, anthonybernardi commented on models/model.py
> +        data = round(self.current_data[id], 1) if self.current_data[id] is not None else self.current_data[id]
since you access self.current_data[id] three times in this one line it might be better to just declare it the line before for readability

2023-03-27 14:50 UTC, anthonybernardi commented on models/model.py
> +        self.pinned_data[id] = DebugPlotValue(name=name, data=[data], unit=unit)
this has the possibility of declaring data as [None], is that fine?

2023-03-27 14:50 UTC, anthonybernardi commented on models/model.py
> +        # update the given pinned data, if we already have 600 values, pop the last one and then insert the newest value at zero
12000 not 600 and explain why

2023-03-27 14:50 UTC, anthonybernardi commented on models/model.py
> +        # update the given pinned data, if we already have 600 values, pop the last one and then insert the newest value at zero
12000 not 600 and explain why maybe by making it a constant at the top

2023-03-27 14:50 UTC, anthonybernardi commented on models/model.py
> +        # update the given pinned data, if we already have 600 values, pop the last one and then insert the newest value at zero
12000 not 600 and explain why maybe by making it a constant at the top

2023-03-27 14:50 UTC, anthonybernardi commented on modes/debug_mode/debug_plot_page.py
> +        self.data: Dict[int, DebugPlotValue] = self.model.pinned_data
why is it called DebugPlotValue if it contains a list of values? should be `DebugPlotLineData` or something

2023-03-27 14:50 UTC, anthonybernardi commented on modes/debug_mode/debug_plot_page.py
> +    def transform_data_to_time(self, data: List[float]) -> List[float]:
python docstring pls

https://github.com/google/styleguide/blob/gh-pages/pyguide.md#383-functions-and-methods

2023-03-27 14:50 UTC, anthonybernardi commented on modes/debug_mode/debug_table_page.py
> +        elif len(self.model.pinned_data) < 6:
6 should probably be a constant like MAX_ITEMS_PINNED or whatever you want to call it

2023-03-27 14:57 UTC, Peyton-McKee commented on models/model.py
> +        self.pinned_data[id] = DebugPlotValue(name=name, data=[data], unit=unit)
yeah i think so, i havnt been able to test it on the pi cuz the wheel isnt made yet

2023-03-27 14:57 UTC, Peyton-McKee commented on models/model.py
> +        # update the given pinned data, if we already have 600 values, pop the last one and then insert the newest value at zero
oop right

2023-03-29 05:16 UTC, Peyton-McKee reviewed
this doesnt work. Pi sucks too badly, should just close it

2023-03-29 22:22 UTC, Peyton-McKee commented
This doesnt work on pi so closing this and the ticket

2023-03-29 22:22 UTC, closed without merging